[package]
name = "specfile-cli"
version = "0.1.0"
authors = ["Tiago Guimarães <tilacog@gmail.com>"]

[dependencies]
structopt = "0.2.3"
diesel = { version = "1.1.1", features = ["postgres"] }
uuid = "0.5.1"
sxd-document = "0.2.6"
sxd-xpath = "0.4.1"
